name: Test

on: push

env:
  db_pass: testpics123

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    services:
      mariadb:
        image: mariadb:10.11.6
        env:
          MYSQL_DATABASE: testpics
          MYSQL_USER: testpics
          MYSQL_PASSWORD: ${{ env.db_pass }}
          MYSQL_ROOT_PASSWORD: ${{ env.db_pass }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        env:
          DB_PASS: ${{ env.db_pass }}
        run: sbt test
